version: '3.8'

services:
  # ----------------------------------------
  # Base de Datos Compartida
  # ----------------------------------------
  mysqldb:
    image: mysql:8.0
    container_name: sabor-gourmet-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sabor_gourmet_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # ----------------------------------------
  # 1. Auth Service
  # ----------------------------------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sabor_gourmet_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=MiClaveSecretaSuperSeguraParaJWT2024SaborGourmet123456789
    depends_on:
      mysqldb:
        condition: service_healthy

  # ----------------------------------------
  # 2. Cliente Service
  # ----------------------------------------
  cliente-service:
    build: ./cliente-service
    container_name: cliente-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sabor_gourmet_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=MiClaveSecretaSuperSeguraParaJWT2024SaborGourmet123456789
    depends_on:
      mysqldb:
        condition: service_healthy

  # ----------------------------------------
  # 3. Mesa Service
  # ----------------------------------------
  mesa-service:
    build: ./mesa-service
    container_name: mesa-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sabor_gourmet_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=MiClaveSecretaSuperSeguraParaJWT2024SaborGourmet123456789
    depends_on:
      mysqldb:
        condition: service_healthy

  # ----------------------------------------
  # 4. Audit Service
  # ----------------------------------------
  audit-service:
    build: ./audit-service
    container_name: audit-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sabor_gourmet_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=MiClaveSecretaSuperSeguraParaJWT2024SaborGourmet123456789
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysql_data: